"""
cwyde_indication_detector — promotes entities to INDICATION category.

Two detection paths:
1. Direct: entity already mapped to INDICATION via medspacy_category_map.yaml
2. Backfill: run language-specific indication patterns on the sentence span,
   catching cases where base ConText missed the rule-out trigger

Runs second in the cwyde pipeline, after category_mapper.
"""

from __future__ import annotations

import re
import logging

from spacy.language import Language
from spacy.tokens import Doc

from cwyde.categories import AssertionCategory

logger = logging.getLogger(__name__)


@Language.factory(
    "cwyde_indication_detector",
    default_config={"lang": "en", "patterns": None},
)
def create_indication_detector(nlp: Language, name: str, lang: str, patterns):
    return IndicationDetectorComponent(lang=lang, patterns=patterns)


class IndicationDetectorComponent:
    def __init__(self, lang: str = "en", patterns=None):
        self._lang = lang
        self._patterns = patterns  # PatternFile or None (lazy load from KB)
        self._compiled: list[re.Pattern] | None = None

    def _ensure_patterns(self):
        if self._compiled is not None:
            return
        if self._patterns is None:
            from cwyde_knowledge import default_indication_patterns
            self._patterns = default_indication_patterns(self._lang)
        self._compiled = [
            re.compile(p.pattern, re.IGNORECASE) for p in self._patterns.patterns
        ]

    def _sentence_matches(self, text: str) -> bool:
        return any(pat.search(text) for pat in self._compiled)

    def __call__(self, doc: Doc) -> Doc:
        self._ensure_patterns()

        for ent in doc.ents:
            if ent._.cwyde_assertion_category == AssertionCategory.INDICATION:
                ent._.cwyde_is_indication = True
                continue

            sent = ent.sent
            if self._sentence_matches(sent.text):
                ent._.cwyde_assertion_category = AssertionCategory.INDICATION
                ent._.cwyde_is_indication = True
                ent._.cwyde_modal_formula = None  # regenerated by consistency_checker
                ent._.cwyde_resolution_trace.append(
                    {"step": "indication_detector", "result": "INDICATION", "reason": "backfill pattern matched"}
                )
                logger.debug("Indication backfill: %r in %r", ent.text, sent.text)

        return doc
